### ISSUE TITLE
与Cyclic不兼容问题

### ISSUE THREAD

**Issue by jukebox-www** [PorPit/UltimateStack#12]
终极叠加UltimateStack-1.12.2-1.3.1 最新版 不兼容

SpartanWeaponry-1.12.2-beta-1.3.8 最新版
https://www.curseforge.com/minecraft/mc-mods/spartan-weaponry
<spartanweaponry:material:2><spartanweaponry:material:1><spartanweaponry:material:0>
这三个物品属于模组武器基础材料，不管怎么修改上限都是64

Cyclic-1.12.2-1.19.18最新版
https://www.curseforge.com/minecraft/mc-mods/cyclic
与大部分能放进物品的机器不兼容，表现为放一个物品（原版上限64，此模组修改为99，999等）进入机器格子后这个物品变成64个
机器列表（应该是全部）：
        cyclicmagic:block_workbench
        cyclicmagic:solidifier
        cyclicmagic:harvester_block
        cyclicmagic:placer_block
        cyclicmagic:block_vacuum
        cyclicmagic:block_miner_smart
        cyclicmagic:block_library
        cyclicmagic:block_enchanter
        cyclicmagic:block_user
        cyclicmagic:builder_block
        cyclicmagic:melter
        cyclicmagic:uncrafting_block
还有模组背包一格只能放64个问题，如cyclicmagic:inventory_food吃蛋糕获得背包，还有
Grim Pack模组的https://www.curseforge.com/minecraft/mc-mods/grim-pack
grimpack:backpack背包grimpack:pellet_bag弹弓弹药包

最后，我将所有可堆叠物品上限修改为999，每次打开、进入游戏后没有问题，游戏里物品上限成功修改为999，但是config文件夹的UltimateStack文件夹都会出现例如OreMaxStackSetting.cfg_20191229_233023的错误文件，每打开一次都有
我很喜欢这个模组，我认为它是美的

**Comment by PorPit** [comment]
目前打算使用Mixin重写mod 到时候我会检查此问题~

**Comment by jukebox-www** [comment]
我好像发现了新的堆叠模组，已经解决了这个问题，叫stackup!，mcbbs已经有人搬运了，现在它是1.12.2与 1.13版本------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;PorPit&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年7月27日(星期一) 下午2:23
收件人:&nbsp;&quot;PorPit/UltimateStack&quot;<UltimateStack@noreply.github.com&gt;;
抄送:&nbsp;&quot;jukebox-www&quot;<2874610314@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PorPit/UltimateStack] 与Cyclic不兼容问题 (#12)

**Comment by PorPit** [comment]
已更新发布 请看论坛帖子 或者直接在github下载页获取下载地址
如果这个bug还有存在请回复告诉我
