### ISSUE TITLE
与自定义NPCMOD出现不兼容问题

### ISSUE THREAD

**Issue by oPpGgG** [PorPit/UltimateStack#13]
如题，而且这里的不兼容性并非是指无法放入或取出堆叠的物品
而是任何物品似乎在NPC眼中都变成了相同物品...
可能不是很易懂,我举个例子
我在服务器里放了一个铁匠,,商人职业,设置10个金锭可以拿来换1个钻石甲
然后前来的玩家会发现，10个面包居然也能当金锭,等价买1个钻石甲
相同的，我做一个做菜的商人npc,比如2个面包可以买1个蜂蜜面包
结果玩家发现可以拿2个铁锭 或者金锭 或者土豆 或者鸡肉 买1个蜂蜜面包...
最后发现只能删除这个mod解决
我是刚刚在自己的海绵服发现这个问题的,还不清楚其他情况下会不会这样.
![1](https://user-images.githubusercontent.com/61931507/76159437-6903db00-615b-11ea-9628-945b66a4806f.jpg)
![2](https://user-images.githubusercontent.com/61931507/76159439-6b663500-615b-11ea-8699-d21b45b8d179.jpg)

**Comment by PorPit** [comment]
目前打算使用Mixin重写mod 到时候我会检查此问题~

**Comment by PorPit** [comment]
已更新发布 请看论坛帖子 或者直接在github下载页获取下载地址
如果这个bug还有存在请回复告诉我
