### ISSUE TITLE
不兼容巨型箱子

### ISSUE THREAD

**Issue by daiaji** [PorPit/UltimateStack#14]
![图片](https://user-images.githubusercontent.com/25875791/76757736-21b4c480-67c3-11ea-94b6-4b0b018ad5f7.png)
如你所见……
这是更多箱子附加的黑耀石巨型箱

**Comment by PorPit** [comment]
目前打算使用Mixin重写mod 到时候我会考虑兼容此模组

**Comment by yeongpin** [comment]
可以搭配StackUp模組來支持堆叠

**Comment by PorPit** [comment]
已更新发布 请看论坛帖子 或者直接在github下载页获取下载地址
如果这个bug还有存在请回复告诉我

**Comment by daiaji** [comment]
@PorPit 我迁移到1.16了……
进行不了长时间的测试
