### ISSUE TITLE
和多页箱子不兼容

### ISSUE THREAD

**Issue by zhouyanan2002** [PorPit/UltimateStack#18]
和多页箱子不兼容如果双击堆叠上了会卡数量

**Comment by PorPit** [comment]
目前打算使用Mixin重写mod 到时候我会考虑兼容此模组

**Comment by PorPit** [comment]
已更新发布  请看论坛帖子 或者直接在github下载页获取下载地址
如果这个bug还有存在请回复告诉我

**Comment by zhouyanan2002** [comment]
终极堆叠目前还存在BUG，前置310版本还有本体加入会导致直接崩溃，
