### ISSUE TITLE
与其他模组不兼容导致BUG问题

### ISSUE THREAD

**Issue by BrokenDawn627** [PorPit/UltimateStack#3]
与[Cyclic](https://minecraft.curseforge.com/projects/cyclic?gameCategorySlug=mc-mods&projectID=239286)模组不兼容
表现为：
1.>64个的物品放入容器中变为64个
2.可用来刷物品，即一个物品会变为1000个
比如我造一个自动鱼栏，使用管道抽取到箱子，然后你就可以看见1000条、1000条的鱼钓上来，泥炭农场和发电机同样只放一个物品就判定为64个等等

另外 与匠魂的工作站不兼容
表现为：>64个的物品放入容器中变为64个

**Comment by PorPit** [comment]
感谢反馈  有空会处理一下~

**Comment by PorPit** [comment]
抱歉  前段时间没有时间  目前打算使用Mixin重写mod   到时候我会一并兼容你表示的问题

**Comment by PorPit** [comment]
已更新发布 请看论坛帖子 或者直接在github下载页获取下载地址
如果这个bug还有存在请回复告诉我
