### ISSUE TITLE
与galacticraft core 冲突 

### ISSUE THREAD

**Issue by CATXYLS** [PorPit/UltimateStack#8]
使用堆叠过的物品用shift放入机器会发生崩溃

日志:
[crash-2019-10-27_17.28.34-client.txt](https://github.com/PorPit/UltimateStack/files/3775690/crash-2019-10-27_17.28.34-client.txt)

**Comment by CATXYLS** [comment]
---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 2019-10-27 17:28:42 CST
Description: Updating screen events

java.lang.NullPointerException
    at micdoodle8.mods.galacticraft.core.inventory.ContainerCircuitFabricator.mergeEven(ContainerCircuitFabricator.java:260)
    at micdoodle8.mods.galacticraft.core.inventory.ContainerCircuitFabricator.transferStackInSlot(ContainerCircuitFabricator.java:130)
    at net.minecraft.inventory.Container.slotClick(Container.java:246)
    at net.minecraft.client.multiplayer.PlayerControllerMP.windowClick(PlayerControllerMP.java:566)
    at net.minecraft.client.gui.inventory.GuiContainer.handleMouseClick(GuiContainer.java:638)
    at net.minecraft.client.gui.inventory.GuiContainer.mouseClicked(GuiContainer.java:392)
    at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:533)
    at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:501)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1759)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected screen --
  Screen name: micdoodle8.mods.galacticraft.core.client.gui.container.GuiCircuitFabricator

-- Affected level --
  Level name: MpServer
  All players: 1 total; [GCEntityClientPlayerMP['cat'/230465, l='MpServer', x=-15.30, y=64.00, z=237.81]]
  Chunk stats: MultiplayerChunkCache: 289, 289
  Level seed: 0
  Level generator: ID 00 - default, ver 1. Features enabled: false
  Level generator options: 
  Level spawn location: World: (-255,64,268), Chunk: (at 1,4,12 in -16,16; contains blocks -256,0,256 to -241,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
  Level time: 3637232 game time, 3715934 day time
  Level dimension: 0
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
  Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
  Forced entities: 57 total; [EntitySkeleton['骷髅'/258566, l='MpServer', x=-37.50, y=13.00, z=308.50], EntitySkeleton['骷髅'/258565, l='MpServer', x=-58.50, y=13.00, z=290.50], EntityZombie['僵尸'/236815, l='MpServer', x=-13.41, y=62.05, z=248.13], EntityBat['蝙蝠'/254763, l='MpServer', x=-21.30, y=17.87, z=279.61], GCEntityClientPlayerMP['cat'/230465, l='MpServer', x=-15.30, y=64.00, z=237.81], EntitySkeleton['骷髅'/258869, l='MpServer', x=11.50, y=14.00, z=291.50], EntityWolf['狼'/230471, l='MpServer', x=-86.43, y=64.00, z=252.70], EntityBoat['船'/230470, l='MpServer', x=-88.31, y=62.52, z=225.13], EntityWolf['狼'/230475, l='MpServer', x=-84.91, y=64.00, z=250.70], EntityWolf['狼'/230474, l='MpServer', x=-80.78, y=64.00, z=250.45], EntityWolf['狼'/230473, l='MpServer', x=-82.85, y=64.00, z=251.25], EntityWolf['狼'/230472, l='MpServer', x=-81.52, y=64.00, z=250.15], EntityWolf['狼'/230479, l='MpServer', x=-84.23, y=64.00, z=250.80], EntityWolf['狼'/230478, l='MpServer', x=-86.19, y=64.00, z=251.20], EntityWolf['狼'/230477, l='MpServer', x=-86.91, y=64.00, z=251.65], EntityWolf['狼'/230476, l='MpServer', x=-85.65, y=64.00, z=250.18], EntitySpider['蜘蛛'/246604, l='MpServer', x=-2.50, y=31.00, z=258.50], EntityWolf['狼'/230483, l='MpServer', x=-82.17, y=64.00, z=250.73], EntityWolf['狼'/230482, l='MpServer', x=-83.89, y=64.00, z=249.55], EntityWolf['狼'/230481, l='MpServer', x=-87.41, y=64.25, z=252.70], EntityWolf['狼'/230480, l='MpServer', x=-83.56, y=64.00, z=250.48], EntityWolf['狼'/230486, l='MpServer', x=-82.93, y=64.00, z=249.74], EntitySkeleton['骷髅'/258902, l='MpServer', x=24.50, y=63.00, z=198.50], EntityWolf['狼'/230485, l='MpServer', x=-84.51, y=64.00, z=251.47], EntityWolf['狼'/230484, l='MpServer', x=-86.01, y=64.00, z=252.06], EntityItem['item.tile.goldenRail'/262749, l='MpServer', x=-52.13, y=64.98, z=246.50], EntityItem['item.tile.goldenRail'/262750, l='MpServer', x=-52.13, y=64.31, z=246.05], EntityLatchedRenderer['不明'/256869, l='MpServer', x=-15.30, y=64.00, z=237.81], EntityItem['item.tile.goldenRail'/230510, l='MpServer', x=-52.50, y=66.13, z=250.88], EntitySkeletonHorse['骷髅马'/230509, l='MpServer', x=-62.04, y=64.00, z=167.13], EntitySkeletonHorse['骷髅马'/230508, l='MpServer', x=-61.14, y=64.00, z=232.21], EntityItem['item.tile.goldenRail'/262768, l='MpServer', x=-53.05, y=65.39, z=246.26], EntityItem['item.tile.goldenRail'/262780, l='MpServer', x=-51.87, y=67.00, z=245.95], EntityCreeper['爬行者'/252538, l='MpServer', x=31.50, y=13.00, z=228.50], EntitySkeleton['骷髅'/260218, l='MpServer', x=62.53, y=67.00, z=210.30], EntityItem['item.tile.goldenRail'/262791, l='MpServer', x=-50.84, y=67.00, z=246.62], EntityItem['item.tile.goldenRail'/262785, l='MpServer', x=-53.78, y=67.00, z=245.99], EntityItem['item.tile.goldenRail'/262786, l='MpServer', x=-53.16, y=65.65, z=247.59], EntitySkeleton['骷髅'/258698, l='MpServer', x=2.50, y=13.00, z=286.50], EntityCreeper['爬行者'/258703, l='MpServer', x=-3.50, y=13.00, z=292.50], EntityCreeper['爬行者'/258702, l='MpServer', x=-1.50, y=13.00, z=291.50], EntityCreeper['爬行者'/258701, l='MpServer', x=-4.50, y=13.00, z=289.50], EntityItem['item.tile.goldenRail'/262795, l='MpServer', x=-52.49, y=67.00, z=247.18], EntityItem['item.tile.goldenRail'/262804, l='MpServer', x=-54.53, y=67.11, z=245.81], EntityItem['item.tile.goldenRail'/262803, l='MpServer', x=-53.86, y=67.30, z=246.51], EntityItem['item.tile.goldenRail'/262815, l='MpServer', x=-52.40, y=67.55, z=246.50], EntityItem['item.tile.goldenRail'/262809, l='MpServer', x=-50.62, y=67.59, z=246.86], EntityItem['item.tile.goldenRail'/262810, l='MpServer', x=-50.46, y=67.71, z=245.80], EntityItem['item.tile.goldenRail'/262811, l='MpServer', x=-50.52, y=67.40, z=244.66], EntityItem['item.tile.goldenRail'/262821, l='MpServer', x=-54.60, y=67.55, z=246.28], EntityItem['item.tile.goldenRail'/262822, l='MpServer', x=-54.52, y=67.73, z=247.55], EntityItem['item.tile.goldenRail'/262823, l='MpServer', x=-54.46, y=67.67, z=248.43], EntityItem['item.tile.goldenRail'/262816, l='MpServer', x=-52.49, y=67.46, z=245.55], EntityItem['item.tile.goldenRail'/262817, l='MpServer', x=-52.49, y=67.62, z=245.28], EntityItem['item.tile.goldenRail'/247742, l='MpServer', x=-50.88, y=66.13, z=250.88], EntityEnderman['末影人'/246214, l='MpServer', x=28.50, y=64.00, z=194.50], EntityBat['蝙蝠'/247782, l='MpServer', x=-18.25, y=35.10, z=230.75]]
  Retry entities: 0 total; []
  Server brand: fml,forge
  Server type: Integrated singleplayer server

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_231, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 11098529544 bytes (10584 MB) / 13925089280 bytes (13280 MB) up to 14680064000 bytes (14000 MB)
  JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx14000m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
  IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
  FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_E3 86 mods loaded, 86 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                                | Version                  | Source                                            | Signature                                |
       |:------ |:--------------------------------- |:------------------------ |:------------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft                         | 1.12.2                   | minecraft.jar                                     | None                                     |
       | LCHIJA | mcp                               | 9.42                     | minecraft.jar                                     | None                                     |
       | LCHIJA | FML                               | 8.0.99.99                | forge-1.12.2-14.23.5.2847.jar                     | None                                     |
       | LCHIJA | forge                             | 14.23.5.2847             | forge-1.12.2-14.23.5.2847.jar                     | None                                     |
       | LCHIJA | jecharacters                      | 1.12.0-3.3.0             | [JECH]JustEnoughCharacters-1.12.0-3.3.0.jar       | None                                     |
       | LCHIJA | creativecoredummy                 | 1.0.0                    | minecraft.jar                                     | None                                     |
       | LCHIJA | smoothfontcore                    | mc1.12.2-1.16            | minecraft.jar                                     | None                                     |
       | LCHIJA | micdoodlecore                     |                          | minecraft.jar                                     | None                                     |
       | LCHIJA | PPDummy                           | 1.0.0                    | minecraft.jar                                     | None                                     |
       | LCHIJA | smoothfont                        | mc1.12.2-1.16.2          | [平滑字体]SmoothFont-mc1.12.2-1.16.2.jar              | None                                     |
       | LCHIJA | deconstruction                    | 3.0.4                    | [MC1.12.2]DeconTable-3.0.4.jar                    | None                                     |
       | LCHIJA | waila                             | 1.8.26                   | [信息显示]Hwyla-1.8.26-B41_1.12.2.jar                 | None                                     |
       | LCHIJA | creativecore                      | 1.9.9                    | [前置]CreativeCore_v1.9.37_mc1.12.2.jar             | None                                     |
       | LCHIJA | ctm                               | MC1.12.2-0.3.3.22        | [前置]CTM-MC1.12.2-0.3.3.22.jar                     | None                                     |
       | LCHIJA | cyclopscore                       | 1.0.2                    | [前置]CyclopsCore-1.12.2-1.0.2.jar                  | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | LCHIJA | ichunutil                         | 7.1.4                    | [前置]iChunUtil-1.12.2-7.1.4.jar                    | None                                     |
       | LCHIJA | mcmultipart                       | 2.5.3                    | [前置]MCMultiPart-2.5.3.jar                         | None                                     |
       | LCHIJA | vanillafix                        | 1.0.10-SNAPSHOT          | [崩溃修复]VanillaFix-1.0.10-99.jar                    | None                                     |
       | LCHIJA | lootbags                          | 2.5.7                    | [战利品]LootBags-1.12.2-2.5.7.jar                    | None                                     |
       | LCHIJA | flammpfeil.slashblade             | mc1.12-r16               | [拔刀剑]SlashBlade-mc1.12-r16.jar                    | None                                     |
       | LCHIJA | slashblade_addon                  | 1.0.6                    | [拔刀剑附属]SJAP_V1.0.6.1_MC1.12.2.jar                 | None                                     |
       | LCHIJA | baubles                           | 1.5.2                    | Baubles-1.12-1.5.2.jar                            | None                                     |
       | LCHIJA | endercore                         | 1.12.2-0.5.72            | EnderCore-1.12.2-0.5.72.jar                       | None                                     |
       | LCHIJA | jei                               | 4.15.0.269               | jei_1.12.2-4.15.0.269.jar                         | None                                     |
       | LCHIJA | codechickenlib                    | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | redstoneflux                      | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal.jar           | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | cofhcore                          | 4.6.3                    | CoFHCore-1.12.2-4.6.3.27-universal.jar            | None                                     |
       | LCHIJA | cofhworld                         | 1.3.1                    | CoFHWorld-1.12.2-1.3.1.7-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | thermalfoundation                 | 2.6.3                    | ThermalFoundation-1.12.2-2.6.3.27-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | thermalexpansion                  | 5.5.4                    | ThermalExpansion-1.12.2-5.5.4.43-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | enderio                           | 5.1.52                   | EnderIO-1.12.2-5.1.52.jar                         | None                                     |
       | LCHIJA | enderiointegrationtic             | 5.1.52                   | EnderIO-1.12.2-5.1.52.jar                         | None                                     |
       | LCHIJA | mantle                            | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                          | None                                     |
       | LCHIJA | tconstruct                        | 1.12.2-2.12.0.157        | TConstruct-1.12.2-2.12.0.157.jar                  | None                                     |
       | LCHIJA | wailaharvestability               | 1.1.12                   | [显示拓展]WailaHarvestability-mc1.12-1.1.12.jar       | None                                     |
       | LCHIJA | texfix                            | 4.0                      | [材质修复]TexFix+V-1.12-4.0.jar                       | None                                     |
       | LCHIJA | customskinloader                  | 14.7                     | [皮肤补丁]CustomSkinLoader_Forge-14.7.jar             | None                                     |
       | LCHIJA | i18nmod                           | 1.12.2-1.0.7             | [自动汉化]i18nupdatemod-1.12.2-1.0.7.jar              | None                                     |
       | LCHIJA | torohealthmod                     | 1.12.2-11                | [血条显示]torohealth-1.12.2-11.jar                    | None                                     |
       | LCHIJA | veinminer                         | 0.38.2                   | [连锁挖矿]VeinMiner-1.12-0.38.2.647+b31535a.jar       | None                                     |
       | LCHIJA | veinminermodsupport               | 0.38.2                   | [连锁挖矿]VeinMiner-1.12-0.38.2.647+b31535a.jar       | None                                     |
       | LCHIJA | ic2                               | 2.8.187-ex112            | industrialcraft-2-2.8.187-ex112 (1).jar           | de041f9f6187debbc77034a344134053277aa3b0 |
       | LCHIJA | mekanism                          | 1.12.2-9.4.13.349        | [通用机械]Mekanism-1.12.2-9.4.13.349.jar              | None                                     |
       | LCHIJA | mekanismgenerators                | 9.4.11                   | [通用机械发电机]MekanismGenerators-1.12.2-9.4.13.349.jar | None                                     |
       | LCHIJA | mekanismtools                     | 9.4.11                   | [通用机械工具]MekanismTools-1.12.2-9.4.13.349.jar       | None                                     |
       | LCHIJA | advanced_solar_panels             | 4.3.0                    | Advanced+Solar+Panels-4.3.0.jar                   | None                                     |
       | LCHIJA | galacticraftcore                  | 4.0.2.238                | GalacticraftCore-1.12.2-4.0.2.238.jar             | None                                     |
       | LCHIJA | galacticraftplanets               | 4.0.2.238                | Galacticraft-Planets-1.12.2-4.0.2.238.jar         | None                                     |
       | LCHIJA | asmodeuscore                      | 0.0.10                   | AsmodeusCore-1.12.2-0.0.11.jar                    | None                                     |
       | LCHIJA | betterbuilderswands               | 0.11.1                   | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar   | None                                     |
       | LCHIJA | biomeinfo                         | v1.2.1                   | biomeinfo-1.12.x-v1.2.1.jar                       | None                                     |
       | LCHIJA | blockdrops                        | 1.4.0                    | blockdrops-1.12.2-1.4.0.jar                       | None                                     |
       | LCHIJA | enderiobase                       | 5.1.52                   | EnderIO-1.12.2-5.1.52.jar                         | None                                     |
       | LCHIJA | enderioconduits                   | 5.1.52                   | EnderIO-1.12.2-5.1.52.jar                         | None                                     |
       | LCHIJA | enderioconduitsappliedenergistics | 5.1.52                   | EnderIO-1.12.2-5.1.52.jar                         | None                                     |
       | LCHIJA | enderioconduitsopencomputers      | 5.1.52                   | EnderIO-1.12.2-5.1.52.jar                         | None                                     |
       | LCHIJA | enderioconduitsrefinedstorage     | 5.1.52                   | EnderIO-1.12.2-5.1.52.jar                         | None                                     |
       | LCHIJA | enderiointegrationforestry        | 5.1.52                   | EnderIO-1.12.2-5.1.52.jar                         | None                                     |
       | LCHIJA | enderiointegrationticlate         | 5.1.52                   | EnderIO-1.12.2-5.1.52.jar                         | None                                     |
       | LCHIJA | enderiomachines                   | 5.1.52                   | EnderIO-1.12.2-5.1.52.jar                         | None                                     |
       | LCHIJA | enderiopowertools                 | 5.1.52                   | EnderIO-1.12.2-5.1.52.jar                         | None                                     |
       | LCHIJA | valkyrielib                       | 1.12.2-2.0.20.1          | valkyrielib-1.12.2-2.0.20.1.jar                   | None                                     |
       | LCHIJA | environmentaltech                 | 1.12.2-2.0.20.1          | environmentaltech-1.12.2-2.0.20.1.jar             | None                                     |
       | LCHIJA | etlunar                           | 1.12.2-2.0.20.1          | etlunar-1.12.2-2.0.20.1.jar                       | None                                     |
       | LCHIJA | extrautils2                       | 1.0                      | extrautils2-1.12-1.9.9.jar                        | None                                     |
       | LCHIJA | galaxyspace                       | 2.0.10                   | GalaxySpace-1.12.2-2.0.10.jar                     | None                                     |
       | LCHIJA | gogskybox                         | 1.1-3                    | GoGSkybox-1.12.2.jar                              | None                                     |
       | LCHIJA | jeivillagers                      | 1.0                      | jeivillagers-1.12-1.0.2.jar                       | None                                     |
       | LCHIJA | jeresources                       | 0.9.2.60                 | JustEnoughResources-1.12.2-0.9.2.60.jar           | None                                     |
       | LCHIJA | mjrlegendslib                     | 1.12.2-1.1.9             | MJRLegendsLib-1.12.2-1.1.9.jar                    | b02331787272ec3515ebe63ecdeea0d746653468 |
       | LCHIJA | oversaturation                    | 1.0                      | Oversaturation-1.12.2-1.0.jar                     | None                                     |
       | LCHIJA | projecte                          | 1.12.2-PE1.4.1           | ProjectE-1.12.2-PE1.4.1.jar                       | None                                     |
       | LCHIJA | plustic                           | 7.1.6.1                  | plustic-7.1.6.1.jar                               | None                                     |
       | LCHIJA | ppcore                            | 1.3.0                    | PPCore-1.12.2-1.3.0.jar                           | None                                     |
       | LCHIJA | projectex                         | 1.2.0.39                 | ProjectEX-1.2.0.39.jar                            | None                                     |
       | LCHIJA | thermaldynamics                   | 2.5.5                    | ThermalDynamics-1.12.2-2.5.5.21-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | tinkersjei                        | 1.2                      | tinkersjei-1.2.jar                                | None                                     |
       | LCHIJA | torcherino                        | 7.6                      | torcherino-7.6.jar                                | None                                     |
       | LCHIJA | mrblade                           | 1.61                     | TRblade技术革新 v1.61[MC1.12.2].jar                   | None                                     |
       | LCHIJA | ultimatestack                     | 1.3.1                    | UltimateStack-1.12.2-1.3.1.jar                    | None                                     |
       | LCHIJA | valkyriecompat                    | 1.12.2-2.0.20.1          | valkyriecompat-1.12.2-2.0.20.1.jar                | None                                     |
       | LCHIJA | universalmodifiers                | 1.12.2-1.0.16.1          | valkyrielib-1.12.2-2.0.20.1.jar                   | None                                     |
       | LCHIJA | weaponlevels                      | 2.4.0                    | weaponlevels-2.4.0.jar                            | None                                     |
       | LCHIJA | tinkertoolleveling                | 1.12.2-1.1.0.DEV.b23e769 | yan.jar                                           | None                                     |
       | LCHIJA | candymod                          | 1.1.4                    | candyworld-1.1.4.jar                              | None                                     |
       | LCHIJA | orelib                            | 3.5.2.2                  | [前置]OreLib-1.12.2-3.5.2.2.jar                     | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
  Loaded coremods (and transformers): VanillaFixLoadingPlugin ([崩溃修复]VanillaFix-1.0.10-99.jar)
                                        
                                      CreativePatchingLoader ([前置]CreativeCore_v1.9.37_mc1.12.2.jar)
                                        
                                      CorePlugin ([平滑字体]SmoothFont-mc1.12.2-1.16.2.jar)
                                        bre.smoothfont.asm.Transformer
                                      UltimateStackPatchingLoader (UltimateStack-1.12.2-1.3.1.jar)
                                        com.porpit.ultimatestack.transform.UltimateStackTransformer
                                      JechCore ([JECH]JustEnoughCharacters-1.12.0-3.3.0.jar)
                                        me.towdium.jecharacters.core.JechClassTransformer
                                      ForgePlugin ([皮肤补丁]CustomSkinLoader_Forge-14.7.jar)
                                        customskinloader.forge.TransformerManager
                                      CTMCorePlugin ([前置]CTM-MC1.12.2-0.3.3.22.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      PPPatchingLoader (PPCore-1.12.2-1.3.0.jar)
                                        
                                      MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.238.jar)
                                        micdoodle8.mods.miccore.MicdoodleTransformer
                                      EnderCorePlugin (EnderCore-1.12.2-0.5.72-core.jar)
                                        com.enderio.core.common.transform.EnderCoreTransformer
                                        com.enderio.core.common.transform.SimpleMixinPatcher
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.2.0' Renderer: 'GeForce GTX 650/PCIe/SSE2'
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
                                   - wailaIntegration (Enabled/Not Forced)
  Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                              * Optifine is installed. This is NOT supported.
                             This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
            
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            !!!You are looking at the diagnostics information, not at the crash.       !!!
            !!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  Suspected Mods: Galacticraft Core (galacticraftcore)
  Launched Version: HMCL 3.2.130
  LWJGL: 2.9.4
  OpenGL: GeForce GTX 650/PCIe/SSE2 GL version 4.2.0, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge,LiteLoader'
  Type: Client (map_client.txt)
  Resource Packs: Minecraft-Mod-Language-Modpack.zip
  Current Language: 简体中文 (中国)
  Profiler Position: N/A (disabled)
  CPU: 4x AMD Phenom(tm) II X4 945 Processor
  Client Crashes Since Restart: 1
  Integrated Server Crashes Since Restart: 0

**Comment by CATXYLS** [comment]
![D54~W}({O(4W 7T S 2FX6I](https://user-images.githubusercontent.com/57060497/67632742-8c339980-f8e2-11e9-9398-bf84a01e758a.png)

**Comment by PorPit** [comment]
目前打算使用Mixin重写mod 到时候我检查你说的这个问题

**Comment by PorPit** [comment]
已更新发布 请看论坛帖子 或者直接在github下载页获取下载地址
如果这个bug还有存在请回复告诉我
